source 'https://rubygems.org'

# use local theme gem for testing
gem "chulapa-jekyll", path: "../"

gem 'github-pages', group: :jekyll_plugins
group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
end

gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick"
gem 'faraday-retry'

