source 'https://rubygems.org'	

gem "chulapa-jekyll"
gem "jekyll", "~> 4"
gem "jekyll-github-metadata"
gem 'jekyll-redirect-from'

group :jekyll_plugins do
    gem 'jekyll-algolia', '~> 1.0'
    gem 'jekyll-paginate'
    gem 'jekyll-sitemap'
end
  
